export { default as FlameIcon } from "./FlameIcon.svg";
export { default as BackIcon } from "./BackIcon.svg";
export { default as BookIcon } from "./BookIcon.svg";
export { default as BriefcaseIcon } from "./BriefcaseIcon.svg";
export { default as ChartBarIcon } from "./ChartBarIcon.svg";
export { default as LayersIcon } from "./LayersIcon.svg";
export { default as QuickIcon } from "./QuickIcon.svg";
export { default as RadarIcon } from "./RadarIcon.svg";
export { default as RefreshIcon } from "./RefreshIcon.svg";
export { default as RevisionIcon } from "./RevisionIcon.svg";
export { default as TrophyIcon } from "./TrophyIcon.svg";
export { default as UserIcon } from "./UserIcon.svg";
export { default as CheckIcon } from "./CheckIcon.svg";
export { default as ClockIcon } from "./ClockIcon.svg";
export { default as ListIcon } from "./ListIcon.svg";
export { default as CalendarIcon } from "./CalendarIcon.svg";
export { default as TargetIcon } from "./TargetIcon.svg";
export { default as ChartBarIcons } from "./ChartBarIcons.svg";
export { default as TrophyIcons } from "./TrophyIcons.svg";
export { default as TrendingUpIcon } from "./TrendingUpIcon.svg";
export { default as UploadIcon } from "./UploadIcon.svg";
export { default as SparkleIcon } from "./SparkleIcon.svg";
export { default as Container } from "./Container.svg";
export { default as ArrowLeftIcon } from "./ArrowLeftIcon.svg";
export { default as LightbulbIcon } from "./LightbulbIcon.svg";
export { default as PlayIcon } from "./PlayIcon.svg";
export { default as Open } from "./Open.svg";
export { default as Check } from "./Check.svg";
export { default as RightIcon } from "./RightIcon.svg";
export { default as FileIcon } from "./FileIcon.svg";
export { default as AlertTriangleIcon } from "./AlertTriangleIcon.svg";
export { default as VectorIcon } from "./VectorIcon.svg";
export { default as NoteIcon } from "./NoteIcon.svg";
export { default as LoderIcon } from "./LoderIcon.svg";
export { default as LineIcon } from "./LineIcon.svg";
export { default as Clock } from "./Clock.svg";
export { default as BoltIcon } from "./BoltIcon.svg";
export { default as CrossIcon } from "./CrossIcon.svg";
export { default as BoxIcon } from "./BoxIcon.svg";
export { default as MenuIcon } from "./MenuIcon.svg";
export { default as ChemistryIcon } from "./ChemistryIcon.svg";
export { default as MathIcon } from "./MathIcon.svg";
export { default as PhysicsIcon } from "./PhysicsIcon.svg";
export { default as LabIcon } from "./LabIcon.svg";
export { default as EditIcon } from "./EditIcon.svg";
export { default as Containers } from "./Containers.svg";
export { default as ComputerIcon } from "./ComputerIcon.svg";
export { default as StarIcon } from "./StarIcon.svg";
export { default as ShieldIcon } from "./ShieldIcon.svg";
export { default as EncourageIcon } from "./EncourageIcon.svg";
export { default as GoalIcon } from "./GoalIcon.svg";
export { default as CheckInIcon } from "./CheckIcon.svg";
export { default as CelebrateIcon } from "./CelebrateIcon.svg";
export { default as PushIcon } from "./PushIcon.svg";
export { default as LeftIconcon } from "./LeftIconcon.svg";
export { default as Location } from "./Location.svg";
export { default as CheckIcons } from "./CheckIcons.svg";
export { default as RadarIcons } from "./RadarIcons.svg";
export { default as BriefcaseIcons } from "./BriefcaseIcons.svg";
export { default as CuteIcon } from "./CuteIcon.svg";
export { default as GlobeIcon } from "./GlobeIcon.svg";
export { default as FlaskIcon } from "./FlaskIcon.svg";
export { default as CalculatorIcon } from "./CalculatorIcon.svg";
export { default as AtomIcon } from "./AtomIcon.svg";
export { default as GraduationCapIcon } from "./GraduationCapIcon.svg";
export { default as StarIcons } from "./StarIcons.svg";
export { default as CloudSunIcon } from "./CloudSunIcon.svg";
export { default as SunIcon } from "./SunIcon.svg";
export { default as MinusIcon } from "./MinusIcon.svg";
export { default as PinIcon } from "./PinIcon.svg";
export { default as ConceptualIcon } from "./ConceptualIcon.svg";
export { default as TimeIcon } from "./TimeIcon.svg";
export { default as DiceIcon } from "./DiceIcon.svg";
export { default as UserIcons } from "./UserIcons.svg";
export { default as EmailIcon } from "./EmailIcon.svg";
export { default as LockIcon } from "./LockIcon.svg";
export { default as LinkIcon } from "./LinkIcon.svg";
export { default as TrashIcon } from "./TrashIcon.svg";
export { default as HelpCircleIcon } from "./HelpCircleIcon.svg";
export { default as WhatsApp } from "./WhatsApp.svg";
export { default as MessageIcon } from "./MessageIcon.svg";
export { default as BellIcon } from "./BellIcon.svg";
export { default as EditIcons } from "./EditIcons.svg";
export { default as Patners } from "./Patners.svg";
export { default as Coaching } from "./Coaching.svg";
export { default as CalendarIcons } from "./CalendarIcons.svg";
export { default as Chart} from "./Chart.svg";
export { default as StatsIcon} from "./StatsIcon.svg";
export { default as PracticeIcon} from "./PracticeIcon.svg";
export { default as Book} from "./book.svg";
export { default as Time} from "./Time.svg";
export { default as ConfirmIcon} from "./ConfirmIcon.svg";
export { default as AddTask} from "./AddTask.svg";
export { default as DotIcon} from "./DotIcon.svg";
export { default as Lightbulb} from "./Lightbulb.svg";






